### PR TITLE
Add Dockerhub prefix variable for tag in Github action

### PR DESCRIPTION
**Pull request by Banshee1221**
This will fix my assumption in #618 that the Dockerhub username is the same name used as the Docker package prefix.

This requires a new secret `DOCKER_HUB_PREFIX` to be added to the repository. In this case `DOCKER_HUB_PREFIX`=`convos`.

Apologies for not realising this sooner!

### CODE REVIEW

**Comment by jhthorsen** [comment]
Looks sane 👍

**Review by jhthorsen — CHANGES_REQUESTED** [review]
Please rebase your changes. No reason to have three commits for this.

Looks good otherwise!

Note to merger: I've added the secret to this repo, so it's safe to merge this later on.

**Comment by Banshee1221** [comment]
It appears that my Git skills are not the best!

**Review by jhthorsen — APPROVED** [review]
Ok, I'll squash it on github then 👍

**Pull request merged**
